### PR TITLE
Fix single quotes in framework interpolation

### LINKED ISSUE #339: Bug: inconsistencies when using `pugSingleQuote: false` with `singleQuote: true` in vue SFCs templates
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.19.2                  |
| Prettier  | v2.5.1                  |
| Framework | vue           |
| Node      | v16.13.2                  |
| OS        | mac           |

## Prettier config

```json
{
  "singleQuote": true,
  "pugSingleQuote": false
}
```

```vue
<template lang="pug">
  my-component(:my-prop="someJavascript('here')")
  div {{ someJavascript('here') }}
</template>
```

## Output

After formatting, we obtain:
```pug
my-component(:my-prop="someJavascript('here')")
div {{ someJavascript("here") }}
```
Code between "mustaches" `{{ ... }}` is *not* pug markup but Javascript code, however it does not respect the `singleQuote: true` prettier option.

## Expected Output

Everything between "mustaches" `{{ ... }}` must be treated as Javascript code, so that the `singleQuote: true` prettier option is respected, as follows:
```diff
- div {{ someJavascript("here") }}
+ div {{ someJavascript('here') }}
```

## Additional Context

May be related to https://github.com/prettier/plugin-pug/issues/66 ?

## Minimal repro playground
[issue-prettier-plugin-pug-quotes.zip](https://github.com/prettier/plugin-pug/files/8132294/issue-prettier-plugin-pug-quotes.zip)

### PR DESCRIPTION
**Pull request by qnp**
Fixes #339

### CODE REVIEW

**Comment by Shinigami92** [comment]
Will actively review it in evening or so

**Review by Shinigami92 — APPROVED** [review]

**Comment by Shinigami92** [comment]
GitHub actions doesn't work right now, tested locally against arch linux node v16 :heavy_check_mark:

**Comment by qnp** [comment]
Thanks. Will you ship a 1.19.4 with that ?

**Comment by qnp** [comment]
@Shinigami92 when I was looking deep into the source code, I found that Vue3’s shortand `#` for `v-slot` is not supported. I hence propose you to add it (I can do the dev tonight), and wait it is done to ship the 1.20.0

**Comment by qnp** [comment]
I mean, I did not test it, I just didn't see the appropriate tests & implementation but I had probably missed something. I'll go deeper this evening and come back to you.

**Comment by qnp** [comment]
Ok it is clear now. `#` shorthand works but I guess for another reason, it works because when getting the scope using object desctructuring, whenever `"{ thing }"` is used in a prop it will be considered as `js` and styled:
- `template(v-slot:header="{scope   }")` => `template(v-slot:header="{ scope }")` OK ✅ 
- `template(#header="{scope   }")` => `template(#header="{ scope }")` OK ✅ 
but:
- `div(any-prop="{maybe( 'im').just('a'   ).string  }")` => `div(any-prop="{ maybe('im').just('a').string }")` is it OK ❓

Anyway, this is a very edge case, and who ever wants to pass a string prop which is curly-braces wrapped ?

**Comment by Shinigami92** [comment]
@qnp I slightly reworked the tests https://github.com/prettier/plugin-pug/commit/854a61b3303f978d2ed947639f350a27d77d3ffa :eyes:

**Comment by qnp** [comment]
@Shinigami92 Nice util that `compareFiles` 💪 😉

**Comment by qnp** [comment]
@Shinigami92 do you have an idea of when you could release 1.20.0 ? In the meantime, I could really use the fix for our projects in production but as my vscode plugin has prettier/plugin-pug as an external dependencies (auto-resolved by prettier) I cann bundle the fix manually in it...

**Comment by Shinigami92** [comment]
@qnp Here it is: https://www.npmjs.com/package/@prettier/plugin-pug/v/1.20.0

**Comment by qnp** [comment]
Neat ! Thank you @Shinigami92

**Comment by chrisjansky** [comment]
I suppose this bug is related:

With ```pugSingleQuote``` undefined at first, the following threw an error:
```v-scroll-spy-active="{ class: 'Topic--Active' }"```

Once I define ```pugSingleQuote: true``` it got formatted as:
```v-scroll-spy-active='{ class: 'Topic--Active' }'``` (obviously faulty)

Then once changed to ```pugSingleQuote: false```, it stays the same as before, so throws an error.

Set ```singleQuote: false``` for all cases. What I am doing wrong?

**Comment by Shinigami92** [comment]
@chrisjansky Before your issues goes under in this already closed and merged PR, could you at least open a new issue?
Or fast-forward and just open a new PR that adds a test with your example inside the https://github.com/prettier/plugin-pug/tree/main/tests/issues folder.
That way we can try to find a bug-fix together and fix it.

**Comment by chrisjansky** [comment]
Hi @Shinigami92, thanks for the quick reply–sorry for reopening this issue.

I am not familiar with tests to be honest but I'll try opening a new PR.

**Comment by chrisjansky** [comment]
Added a new PR: #362

**Pull request merged**
