### PR TITLE
Allow "none" as an option for attributeSeparator

### LINKED ISSUE #102: Allow "none" as an option for attributeSeparator
## Request / Idea

pug does not require commas following the attribute definitions, so can we add one more setting option to `attributeSeparator` so it can be `always || as-needed || none` ?

## Input

```pug
container(
  someAttribute="value",
  another="OtherValue"
)
```

## Expected Output

```pug
container(
  someAttribute="value"
  another="OtherValue"
)

```

### PR DESCRIPTION
**Pull request by lehni**
Closes #102

### CODE REVIEW

**Comment by Shinigami92** [comment]
I need to investigate why the checks / tests are not running

**Review by Shinigami92 — CHANGES_REQUESTED** [review]
- You should add a test case were attributes starting with `:` and `@` are on a wrapped own line
- You should add an extra pug-file test that contains e.g. `(click)` (_angular syntax_) as a non first attribute  
  If this tests break with an exception, you should expect this in the tests AND add a warning note for users in the `README.md`

**Comment by Shinigami92** [comment]
Can you try to just use `push` instead of `force-push`? I use squash merges anyway...  
Maybe this will activate the checks

**Comment by lehni** [comment]
Oh yes, sorry about the force-pushes! I will work on this again tomorrow.

**Comment by lehni** [comment]
@Shinigami92 this should be good to go now!

**Review by Shinigami92 — APPROVED** [review]
LGTM, but I need to work on my `.github/workflows/ci.yml` so the checks will be triggered
Will let you know when you need to merge `master` into this branch (or maybe I can do this with a button click)

Edit: ok no button for me :slightly_frowning_face:, so you need to merge the master branch into yours
That includes a CI change and updated dependencies (so also the outdated check will not fail)

**Comment by lehni** [comment]
I'm trying to do so, but dealing with this strange error currently:

```
git push
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/lehni/plugin-pug
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
```

**Comment by lehni** [comment]
The weird part is that I'm not actually using OAuth, I'm using the command line directly?

**Comment by Shinigami92** [comment]
But `git pull` worked?
Try a `rebase` instead :thinking: :eyes:

**Comment by lehni** [comment]
I had to switch fro using `https` to `ssh` for the remote, and now it works. Very strange.

**Comment by lehni** [comment]
@Shinigami92 I finally managed to merge master into this, should go all green shortly 🤞

**Review by Shinigami92 — APPROVED** [review]

**Pull request merged**
