### PR TITLE
Add pug aliased options

### LINKED ISSUE #105: New rule names of aliases for prettier defaults
## Request / Idea
Use new names or aliases for rules that are specific for Pug instead of using default ones.

## Current Configuration

```json
{
  "bracketSpacing": true,
  "overrides": [
    {
      "files": "*.pug",
      "options": {
        "parser": "pug",
        "bracketSpacing": false
      }
    }
  ]
}
```

## Expected Configuration

```json
{
  "bracketSpacing": true,
  "pugBracketSpacing": false
}
```

## Additional Context

Using files override won't work in mixed files, like Vue's Single File Components since it doesn't recognizes Pug templates as a file.

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #105

### CODE REVIEW

**Comment by SkyaTura** [comment]
Thanks for the fast response

**Comment by Shinigami92** [comment]
@SkyaTura Can you provide me a sample `vue` file for `bracketSpacing` option that contains js and pug code?

**Comment by SkyaTura** [comment]
My pain is actually with `singleQuote`:
  
```vue
<template lang="pug">
  // intended not to be single quoted
  ComponentBar(
    foo="bar"
    bar="baz"
  )
</template>

<script>
  export default {
    name: 'FooComponent' // intended to be single quote
  }
</script>
```

**Comment by Shinigami92** [comment]
Good that I asked 😁
doesn't work as expected...
Need to work further

**Comment by SkyaTura** [comment]
> OH WOW! I learned an interesting fact about prettier options :D

Could you mind to share what you've learn? I'm curious 😂

**Comment by Shinigami92** [comment]
@SkyaTura Sure :)

Two things:

1. If you create aliases like `pug*` you also have to define the default values for this new option, otherwise it will not be taken at all
2. It's not really possible to have an option that has a default value of `null` or `undefined` when having a value like `int`  
    I'm currently struggling with prettier's default values, my `pug*` default values and incremental developing without breaking changes

**Comment by SkyaTura** [comment]
Isn't possible to get access to the actual config declaration? Before prettier defaults been applied, so that you could check if there are `pug*` been set?

Or make `pug*` to be strings, so, if they are set you ignore the prettier's default?

_Just wondering here, I don't have any knowledge about prettier plugins yet_ 😰

**Comment by Shinigami92** [comment]
Nope, nothing of this is possible :/

**Comment by Shinigami92** [comment]
Worked on it almost exactly 3 hours 😁
Seems to work

I'm thinking to release a beta `1.6.0-beta.1`

And I also need to update changelog

**Comment by Shinigami92** [comment]
@SkyaTura I released [1.6.0-issue-105.1](https://www.npmjs.com/package/@prettier/plugin-pug/v/1.6.0-issue-105.1) for you
Please test the hell out of it 😈

**Comment by SkyaTura** [comment]
Sure I will

**Comment by SkyaTura** [comment]
It's ~kinda~ working 😰 

I don't know if it's related to this project or I am doing something wrong, but I have this setup:

- A project where I define my team patterns as a eslint-config
- I use prettier plugin to load prettier in eslint
- I use the rules to override prettier's settings

**If** I run locally, on the module, as a test, it goes well, detect errors and fixes them as well.
**If** I run remotely, on a project, nothing happens.

The curious thing about it: using `@latest` works well, using the branch you've created, none of the rules are recognized.

_Bonus: this happens both on eslint and vim plugin_

So, basically, this is my files:

_module/prettier.js_
```js
module.exports = {
  extends: ['plugin:prettier/recommended'],
  plugins: ['prettier'],
  rules: {
    'prettier/prettier': [
      'error',
      {
        trailingComma: 'es5',
        printWidth: 80,
        tabWidth: 2,
        semi: false,
        singleQuote: true,
        endOfLine: 'lf',
        plugins: ['@prettier/plugin-pug'],
        pugSingleQuote: false,
        attributeSeparator: 'as-needed',
        closingBracketPosition: 'new-line',
        commentPreserveSpaces: 'trim-all',
      },
      {
        usePrettierrc: false,
      },
    ],
}
```

_project/.eslintrc.js_
```js
module.exports = {
  root: true,
  extends: [
    '@myOrg/eslint-config/prettier',
  ],
  ignorePatterns: ['node_modules', 'lib', 'dist', '.thalamus', '.nuxt'],
  rules: {},
}
```

If this isn't related, sorry :P

**Comment by Shinigami92** [comment]
I need to fix a little thingy, but this will not affect you :)
Just the default assumption of non boolean default values needs to be changed

Cause currently it's not possible to define `{ "printWidth": xy, "pugPrintWidth": 80 }`, this would always take `xy` for everything

**Comment by Shinigami92** [comment]
Dafuq?
Setting `"pugSingleQuote": true` results in `Invalid --pug-single-quote value. Expected null, false or "", but received true.` :eyes:  
I thing this is a bug in prettier  😲

And I also have a bug when using
```
{
  "singleQuote": true,
  "pugSingleQuote": false
}
```

This produces e.g. `div(:class="{ "pt-2": !dense }")` instead of `div(:class="{ 'pt-2': !dense }")`

Referencing https://github.com/prettier/prettier/issues/9204

**Pull request merged**
